#ifndef FURNITURE_SELL_LAYOUT_H
#define FURNITURE_SELL_LAYOUT_H

#include <stdint.h>
#include <windows.h>

static const char* const MOD_NAME = "Furniture Sale";

static const uint32_t UI_BOOTSTRAP_INTERVAL_MS = 100U;
static const uint32_t UI_TICK_INTERVAL_MS = 16U;
static const int HOOK_PRIORITY = 25;

static const int BUTTON_UPDATE_STOLEN_BYTES = 17; // Button::update trampoline hook bytes stolen...
static const int REBUILD_FURNITURE_LIST_STOLEN_BYTES = 15; // FurnitureBuildingUI::rebuildFurnitureList trampoline hook bytes stolen...

static const UINT_PTR MEW_RVA_FURNITURE_MENU_BUTTON_INIT = 0x001A0EF0ULL; // FurnitureMenuButton::init, used to discover owned-furniture menu buttons...
static const int MEW_RVA_FURNITURE_MENU_BUTTON_INIT_STOLEN_BYTES = 15; // FurnitureMenuButton::init trampoline hook bytes stolen...
static const UINT_PTR MEW_RVA_SAVE_DATA_SINGLETON = 0x013D16E0ULL; // SaveData singleton slot containing owned furniture and house gold...
static const UINT_PTR MEW_RVA_GAME_DATA_SINGLETON = 0x013BE710ULL; // GameData singleton slot used by the furniture-cost resolver...
static const UINT_PTR MEW_RVA_GET_FURNITURE_COST = 0x007B57A0ULL; // Native furniture-cost resolver...
static const UINT_PTR MEW_RVA_COPY_NARROW_STRING_OBJECT = 0x00052410ULL; // Narrow-string copy constructor/helper consumed by cost lookup...
static const UINT_PTR MEW_RVA_REMOVE_OWNED_FURNITURE = 0x002052E0ULL; // SaveData owned-furniture removal helper...
static const UINT_PTR MEW_RVA_REBUILD_FURNITURE_LIST = 0x001A5C60ULL; // FurnitureBuildingUI::rebuildFurnitureList...
static const UINT_PTR MEW_RVA_RESOLVE_FURNITURE_BUILDING_UI_FROM_MENU_BUTTON = 0x000AF1D0ULL; // Native owner lookup from FurnitureMenuButton back to FurnitureBuildingUI...
static const UINT_PTR MEW_RVA_REFRESH_FURNITURE_CACHE = 0x001A5470ULL; // FurnitureBuildingUI's owned-furniture cache refresh routine...
static const UINT_PTR MEW_RVA_SORT_FURNITURE_CACHE = 0x001A5620ULL; // FurnitureBuildingUI's cache sort routine...
static const UINT_PTR MEW_RVA_UPDATE_FURNITURE_NAV_STATE = 0x001A3CB0ULL; // FurnitureBuildingUI's navigation/page-state update routine...
static const UINT_PTR MEW_RVA_GET_AUDIO_SOURCE_FROM_COMPONENT = 0x0004A2B0ULL; // Component::getAudioSource-style helper used before playing UI SFX...
static const UINT_PTR MEW_RVA_AUDIO_SOURCE_PLAY_SOUND_EVENT = 0x009574E0ULL; // AudioSource::PlaySoundEvent...

static const uint32_t OFF_FURNITURE_MENU_BUTTON_ROOT_NODE = 0x38U; // FurnitureMenuButton Button/root node component...
static const uint32_t OFF_FURNITURE_MENU_BUTTON_FURNITURE_ID = 0x48U; // FurnitureMenuButton furniture id...
static const uint32_t OFF_FURNITURE_MENU_BUTTON_PARENT_MANAGER = 0x20U; // FurnitureMenuButton points at the owning FurnitureBuildingUI manager...
static const uint32_t OFF_FURNITURE_MENU_BUTTON_OWNED_VECTOR_COUNT = 0x124U; // FurnitureBuildingUI owned-button vector count, used when pruning a sold button...
static const uint32_t OFF_FURNITURE_MENU_BUTTON_OWNED_VECTOR_DATA = 0x128U; // FurnitureBuildingUI owned-button vector data pointer, (Paired with the count above)...

static const uint32_t OFF_HOUSE_GOLD = 0xB4U; // SaveData stores the house gold total...
static const uint32_t OFF_BUTTON_STATE = 0x2F0U; // Current hover/down/selected state enum...
static const uint32_t OFF_COMPONENT_DELETED = 0x0FU; // Marks a component as deleted for the engine's lifecycle pass...
static const uint32_t OFF_COMPONENT_ENABLED = 0x10U; // Marks a component as enabled/disabled...

static const uint32_t OFF_FURNITURE_BUILDING_UI_ITEM_COUNT = 0x4CU; // FurnitureBuildingUI stores the cached owned-furniture item count...
static const uint32_t OFF_FURNITURE_BUILDING_UI_ITEM_DATA = 0x50U; // FurnitureBuildingUI stores the cached owned-furniture id array pointer...
static const uint32_t OFF_FURNITURE_BUILDING_UI_REDRAW_DIRTY = 0x58U; // FurnitureBuildingUI is the redraw/dirty flag used before list rebuilds...
static const uint32_t OFF_FURNITURE_BUILDING_UI_PAGE_INDEX = 0x7CU; // FurnitureBuildingUI stores the current owned-furniture page index...

static const uint32_t OFF_FURNITURE_META_ID = 0x00U; // Furniture metadata entry stores the furniture id...
static const uint32_t OFF_FURNITURE_META_VECTOR_COUNT = 0x3CU; // SaveData furniture-metadata vector count...
static const uint32_t OFF_FURNITURE_META_VECTOR_DATA = 0x40U; // SaveData furniture-metadata vector data pointer...
static const uint32_t OFF_FURNITURE_META_ITEM_NAME_STRING = 0x08U; // Furniture metadata entry +0x08 stores the narrow item-name string object...
static const uint32_t OFF_FURNITURE_META_FLAGS = 0x28U; // Furniture metadata entry contains flags, bit 1 is treated as the rare flag...

static const uint32_t OFF_UI_ROOT_WRAPPER = 0x18U; // Generic UI wrapper points from a manager/root candidate to its child UI root...
static const uint32_t OFF_UI_ROOT_BUTTON_CONTAINER = 0x08U; // Generic UI root points at the FurnitureMenuButton owner/container in this menu...
static const uint32_t OFF_UI_ROOT_DISPLAY_NODE = 0x38U; // The FurnitureMenuButton root's candidate contains the visible display subtree...

static const uint32_t OFF_FURNITURE_META_DUMP_SCAN_BEGIN = 0x20U; // Start offset for diagnostic metadata uint32 scanning...
static const uint32_t OFF_FURNITURE_META_DUMP_SCAN_END = 0x90U; // End offset for diagnostic metadata uint32 scanning...
static const uint32_t OFF_FURNITURE_META_DUMP_SCAN_STEP = 4U; // Step size for diagnostic metadata uint32 scanning...
static const uint32_t MAX_PLAUSIBLE_META_FIELD_VALUE = 200000U; // Upper bound for logging plausible metadata fields without spamming pointer-sized values...

// Small list of child offsets probed when searching unknown UI root candidates...
static const uint32_t FURNITURE_UI_ROOT_PROBE_OFFSETS[] =
{
    0x00U,
    0x08U,
    0x10U,
    0x18U,
    0x20U,
    0x28U,
    0x30U,
    0x38U,
    0x40U,
    0x48U,
    0x50U
};

static const char* const HOUSE_GOLD_TEXT_NODE_NAME = "house_gold"; // Text node showing the persistent house gold total...
static const char* const FURNITURE_CURRENT_MONEY_TEXT_NODE_NAME = "furnitureCurrentMoney"; // Text node showing the new current money total inside the furniture picker...
static const char* const BUILD_MENU_NODE_NAME = "BuildMenu"; // BuildMenu node searched before playing the "sell coin pulse" animation...
static const char* const FURNITURE_SELL_COIN_PULSE_NODE_NAME = "coinPulseFurnitureSell"; // New MovieClip node used for the "furniture sell coin pulse"...
static const char* const SELL_COIN_SOUND_EVENT_NAME = "MapZoomerCoin_End"; // Sound event played when a furniture sale grants coins...
static const char* const SELL_INFO_CHILD_NAME = "furnitureSellInfo"; // Authored child node containing the owned-furniture sale information...
static const char* const PRICE_CHILD_NAME = "price"; // New child text node that displays the sale price for each furniture...
static const char* const PRICE_LOCALIZATION_KEY = "FURNITURE_OWNED_PRICE"; // Localization key used when writing the sale price value into the price text...

static const int RIGHT_MOUSE_BUTTON_INDEX = 1;

// Maximum tracked live furniture buttons during furniture-picker session...
enum { MAX_TRACKED_FURNITURE_BUTTONS = 512U }; // Fuck you...

#endif